import fs from 'node:fs'
import path from 'node:path'
import matter from 'gray-matter'
import type { Plugin } from 'vite'

export interface ManifestConfig {
  /** Content directory relative to project root */
  contentDir: string
  /** Output manifest file path relative to project root */
  outputPath: string
}

const DEFAULT_CONFIGS: ManifestConfig[] = [
  {
    contentDir: 'src/content/slides',
    outputPath: 'src/content/slides/manifest.gen.ts',
  },
]

function extractFrontmatter(filePath: string): Record<string, unknown> | null {
  try {
    const content = fs.readFileSync(filePath, 'utf-8')
    const { data } = matter(content)
    return data
  } catch {
    return null
  }
}

function generateManifest(root: string, config: ManifestConfig): string {
  const contentDir = path.resolve(root, config.contentDir)

  if (!fs.existsSync(contentDir)) {
    return '// Auto-generated — no content found\nexport const manifest: Record<string, never> = {}\n'
  }

  const entries: Array<{ slug: string; data: Record<string, unknown> }> = []

  const topLevel = fs.readdirSync(contentDir).filter(f => f.endsWith('.mdx'))
  for (const file of topLevel) {
    const filePath = path.join(contentDir, file)
    if (fs.statSync(filePath).isDirectory()) continue
    const data = extractFrontmatter(filePath)
    if (data) {
      entries.push({ slug: file.replace('.mdx', ''), data })
    }
  }

  // Also scan one level of subdirectories for nested content groups.
  const subdirs = fs.readdirSync(contentDir).filter(f => {
    const fp = path.join(contentDir, f)
    return fs.statSync(fp).isDirectory()
  })
  for (const subdir of subdirs) {
    const subdirPath = path.join(contentDir, subdir)
    const subFiles = fs.readdirSync(subdirPath).filter(f => f.endsWith('.mdx'))
    for (const file of subFiles) {
      const data = extractFrontmatter(path.join(subdirPath, file))
      if (data) {
        entries.push({ slug: file.replace('.mdx', ''), data })
      }
    }
  }

  return [
    '// Auto-generated by mdx-manifest-plugin — do not edit manually',
    `export const manifest = ${JSON.stringify(
      Object.fromEntries(entries.map(e => [e.slug, e.data])),
      null,
      2
    )} as const`,
    '',
  ].join('\n')
}

/**
 * Vite plugin that extracts slide-deck MDX frontmatter into a static manifest.
 *
 * Mirrors the atom63.io plugin: it decouples metadata from MDX module loading
 * (so Rollup can code-split decks into lazy chunks) and — critically for os63 —
 * regenerates `manifest.gen.ts` in dev when a deck is added/edited, so new decks
 * actually surface in the picker. The committed manifest is the build input.
 */
export function mdxManifestPlugin(configs: ManifestConfig[] = DEFAULT_CONFIGS): Plugin {
  let root = ''

  return {
    name: 'mdx-manifest-plugin',

    configResolved(config) {
      root = config.root
    },

    buildStart() {
      for (const config of configs) {
        const outputPath = path.resolve(root, config.outputPath)
        const content = generateManifest(root, config)
        const outputDir = path.dirname(outputPath)
        if (!fs.existsSync(outputDir)) {
          fs.mkdirSync(outputDir, { recursive: true })
        }
        fs.writeFileSync(outputPath, content, 'utf-8')
      }
    },

    // In dev, regenerate the manifest when a deck MDX file changes.
    handleHotUpdate({ file }) {
      if (!file.endsWith('.mdx')) return
      for (const config of configs) {
        const contentDir = path.resolve(root, config.contentDir)
        if (file.startsWith(contentDir)) {
          const content = generateManifest(root, config)
          fs.writeFileSync(path.resolve(root, config.outputPath), content, 'utf-8')
        }
      }
    },
  }
}
